Feature/models
wecode-bootcamp-korea/30-1st-ChickIN-backend pull request #1
Opened 2022-03-02 13:20 UTC by jayce-kim1123

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- app 생성 및 modeling

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. users app 생성 및 모델링 작업
2. products app 생성 및 모델링 작업
3. carts app 생성 및 모델링 작업
4. orders app 생성 및 모델링 작업
5. 한 가지의 상품에 여러가지 옵션이 중복될 수 있게 모델링

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- ERD 작성법 상기
- MTM 관계 처리법 상기
- UUID 처음으로 사용 

<br />

## :: 기타 질문 및 특이 사항
- UUID 를 처음 적용하다보니 옵션값을 어떤 걸 주어야 할지 모르겠습니다!

2022-03-02 23:35 UTC, Kang-kyunghun requested changes

2022-03-02 23:35 UTC, Kang-kyunghun commented on products/models.py
> +    purchase_id = models.ForeignKey('Purchase', on_delete=models.CASCADE)
```suggestion
    purchase = models.ForeignKey('Purchase', on_delete=models.CASCADE)
```
foreignkey로 만든 속성은 장고가 자동으로 _id를 붙혀주므로 _id 빼주세요. 
여기뿐만 아니라 다른 곳들 전부 수정해 주세요.

2022-03-02 23:35 UTC, Kang-kyunghun commented on products/models.py
> +    purchase_id = models.ForeignKey('MainCategory', on_delete=models.CASCADE)
```suggestion
    main_category = models.ForeignKey('MainCategory', on_delete=models.CASCADE)
```
속성 이름이 잘못된 것 같네요.

2022-03-02 23:35 UTC, Kang-kyunghun commented on orders/models.py
> +    created_at      = models.DateTimeField(auto_now_add=True)
상태가 바뀌는 시점에 대해서도 알 필요가 있습니다.
updated_at도 추가해 주세요.

2022-03-02 23:35 UTC, Kang-kyunghun commented on orders/models.py
> +    order_status_id = models.ForeignKey('OrderStatus', on_delete=models.CASCADE)
_id 제거해 주세요.

2022-03-02 23:35 UTC, Kang-kyunghun commented on carts/models.py
> +    product_id = models.ForeignKey('Product', on_delete=models.CASCADE)
product가 아니고, option이 와야 할 것 같은데 다시 확인해 주세요.

2022-03-02 23:35 UTC, Kang-kyunghun commented on carts/models.py
> +    updated_at = models.DateTimeField(auto_now=True)
잘못된 것은 아니지만 통상 보기 편하게 created_at과 updated_at 속성은 가장 아래로 내려주는 것이 좋습니다.

2022-03-02 23:35 UTC, Kang-kyunghun commented on carts/models.py
> +    product_id = models.ForeignKey('Product', on_delete=models.CASCADE)
_id 제거해 주세요.

2022-03-03 00:38 UTC, jayce-kim1123 commented on products/models.py
> +    purchase_id = models.ForeignKey('MainCategory', on_delete=models.CASCADE)
복사하고 수정을 안 했나봐요 ㅠㅠ 수정하겠습니다!

2022-03-03 00:41 UTC, jayce-kim1123 commented on carts/models.py
> +    updated_at = models.DateTimeField(auto_now=True)
FK 값보다도 아래에 있어야 하는군요! 수정하겠습니다!

2022-03-03 02:15 UTC, Kang-kyunghun commented
LGTM~!!

2022-03-03 02:15 UTC, merged