[김가람휘] Feature/product list
wecode-bootcamp-korea/30-1st-ChickIN-backend pull request #5
Opened 2022-03-04 03:22 UTC by kimkaramhwi

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [ ] 기능 추가
- [ ] 리뷰 반영
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 (해당 브랜치에서 구현하고자 하는 하나의 목표를 설정합니다.)
- productlistview, productdatailview 구현

<br />

## :: 구현 사항 설명 (작업한 내용을 상세하게 기록합니다.)
1. productlistview 구현
- 전체 상품 필터
- main_category 상품 필터
- sub_category 상품 필터
- 검색한 이름 상품 필터

2. productdatailview 구현
- 각 상품 id의 url로 접속시 그 상품의 정보들을 불러오게 했습니다.

<br />

## :: 성장 포인트 (해당 기능을 구현하며 고민했던 사항이나 새로 알게된 부분, 어려웠던 점 등을 작성합니다.)
- product를 main_category에 따라 필터링하는 것이 어려웠습니다.
- prefetch_related와 selected_related의 사용법이 서툴고 어렵습니다.

<br />

## :: 기타 질문 및 특이 사항
- 상품 상세페이지에서 옵션을 이렇게 불러오는 것이 맞나요?

2022-03-04 04:13 UTC, kimkaramhwi commented
- 전체상품
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/57164712/156697626-0d34fb7a-3b72-42e2-bfaa-ffd7dc1910eb.png">
- main_category 필터
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/57164712/156697682-b8be2253-ac65-4728-b541-de6b1e3c6fdc.png">
- sub_category 필터
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/57164712/156697773-d088612b-6164-4a49-a66d-889570abcaf1.png">
-검색한 상품 이름 필터
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/57164712/156697845-2787d326-48a3-46d6-b1b4-bff8e3fac917.png">

-상품상세페이지
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/57164712/156698014-5df2a0ec-f3fe-400d-9014-3feeee430278.png">
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/57164712/156698059-10935c53-a82c-4593-9954-aace13b036e8.png">

2022-03-04 04:39 UTC, Kang-kyunghun requested changes

2022-03-04 04:39 UTC, Kang-kyunghun commented on products/views.py
> +            products = Product.objects.select_related('sub_category').filter(sub_category_id=sub_category)\
1. products = Product.objects.all()로 가져온 뒤에 다시 아래에서 재정의 한 이유가 무엇인가요?
2. prefetch_related와 select_related를 사용한 이유를 코멘트로 남겨 주세요.

2022-03-04 04:39 UTC, Kang-kyunghun commented on products/views.py
> +            searching     = request.GET.get('name', None)
쿼리스트링으로 오는 파라미터들을 잘 가져 오셨습니다. 이제 이것들을 이용해서 filter을 구현해야 되는데, django에는 Q 객체라는 것이 있습니다. 복잡한 filter을 구현할 때 사용하는데, 공식 문서를 참고해 Q을 이용하여 filter을 구현해 보세요. 그러면 아래 코드보다 좀 더 깔끔한 코드가 나올 것 같습니다.

2022-03-04 04:39 UTC, Kang-kyunghun commented on products/views.py
> +                    )
append를 이용하지 말고 list comprehension을 이용해서 만들어 보세요.

2022-03-04 04:39 UTC, Kang-kyunghun commented on products/views.py
> +            return JsonResponse({'message':'TypeError'}, status=400)
해당 2개 예외처리를 추가한 이유를 코멘트로 남겨주세요.

2022-03-04 11:07 UTC, kimkaramhwi commented on products/views.py
> +                    )
넵 수정했습니다!

2022-03-04 11:44 UTC, kimkaramhwi commented on products/views.py
> +            products = Product.objects.select_related('sub_category').filter(sub_category_id=sub_category)\
1.  모든 상품들의 객체를 불러온 후 쿼리스트링으로 오는 파라미터에 따라 불러오는 상품이 달라야 하기 때문에 그에 맞게 불러올 수 있도록 파라미터에 따라 상품들을 재정의 해주었습니다.

2. select_related, prefetch_related는 하나의 쿼리셋을 가져올 때 연관되어 있는 객체들을 미리 불러올 수 있고 이 데이터들을 cache에 저장하므로 매 쿼리마다 db에 접근하지 않아도 돼서 성능을 높일 수 있기 때문에 사용했습니다.

2022-03-04 12:19 UTC, kimkaramhwi commented on products/views.py
> +            return JsonResponse({'message':'TypeError'}, status=400)
attributeerror는 메서드가 잘못되었거나 잘못된 속성을 사용했을 때 발생하는 예외이므로 추가했습니다. 코드를 수정하면서 잘못된 메소드를 작성했을 때 이 오류가 떴습니다.

typeerror는 int형식에 문자가 들어갔을 경우 서로 다른 타입이므로 예외에 추가하려고 했으나 실제로 작성하고 값을 받아보면서 list뷰에서 이 오류가 발생하진 않았습니다 빼도 될 것 같습니다.

2022-03-04 13:41 UTC, kimkaramhwi commented on products/views.py
> +            searching     = request.GET.get('name', None)
넵 수정하겠습니다!

2022-03-06 08:34 UTC, Kang-kyunghun requested changes

2022-03-06 08:34 UTC, Kang-kyunghun commented on products/views.py
> +            sort          = request.GET.get('sort', None)
sort 값이 안 들어 왔을 때를 대비해 기본값을 정해주는 것이 좋습니다.

2022-03-06 08:34 UTC, Kang-kyunghun commented on products/views.py
> +            products = Product.objects.all()
```suggestion

```
Q와 filter의 조합으로 products 가 바뀌므로 제거해도 괜찮을 것 같네요.

2022-03-06 08:34 UTC, Kang-kyunghun commented on products/views.py
> +
이 2개를 합칠 수 있는 방법을 생각해 보면 좋을 것 같아요.

2022-03-06 08:37 UTC, Kang-kyunghun commented
전체적으로 Q()나 pagination등 잘 적용 했습니다.
조금 더 가독성 측면에서 좋게 수정하면 좋을 것 같아요.

전체 구조를 다음과 같이 한 번 바꿔보세요.

1. front에서 받는 데이터 처리
2. Q를 이용하여 조건 만들기
3. products = Product.objects.filter(q).order_by()[offset:offset+limit] 을 딱 한 번만 사용해서 중복 코드제거
(2번 Q()에서 상황에 맞는 조건들을 만드는 코드가 다 있어야 합니다. 마지막에 다시 if/else로 나누면 안 되고요)

2022-03-06 08:48 UTC, kimkaramhwi commented on products/views.py
> +            products = Product.objects.all()
넵 수정하겠습니다!

2022-03-06 09:10 UTC, kimkaramhwi commented on products/views.py
> +
넵 알겠습니다!

2022-03-06 09:10 UTC, kimkaramhwi commented on products/views.py
> +            sort          = request.GET.get('sort', None)
기본값 id순으로 수정하겠습니다!

2022-03-06 09:26 UTC, kimkaramhwi commented on products/views.py
> +            sort          = request.GET.get('sort', None)
넵 id값을 기본값으로 정하겠습니다!

2022-03-07 11:24 UTC, Kang-kyunghun commented
LGTM~~!

2022-03-07 11:24 UTC, merged